#include "tinyml_model.h"
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Include the model array (generated by train_model.py)
#include "model.cc"

static tflite::MicroErrorReporter micro_error_reporter;
static tflite::AllOpsResolver resolver;
static tflite::MicroInterpreter static_interpreter(
    tflite::GetModel(model_tflite), resolver, tensor_arena, kTensorArenaSize);
static TfLiteTensor* input = nullptr;
static TfLiteTensor* output = nullptr;

void init_tinyml_model(void) {
    input = static_interpreter.input(0);
    output = static_interpreter.output(0);
    static_interpreter.AllocateTensors();
}

int run_inference(const float* features) {
    // Copy 7 features to input tensor
    for (int i = 0; i < 7; i++) {
        input->data.f[i] = features[i];
    }
    static_interpreter.Invoke();
    // Assume output is integer class 0,1,2
    return output->data.i32[0];
}
